import { authApi } from '@/features/auth/api/auth.api'
import { aiTestingApi } from '@/features/ai-testing/api/aiTesting.api'
import { apiAutomationApi } from '@/features/api-automation/api/apiAutomation.api'
import { baseServicesApi } from '@/features/base-services/api/baseServices.api'
import { functionTestingApi } from '@/features/test-cases/api/functionTesting.api'
import { projectsApi } from '@/features/projects/api/projects.api'
import { requirementsApi } from '@/features/requirements/api/requirements.api'
import { uiAutomationApi } from '@/features/ui-automation/api/uiAutomation.api'

export type { LoginResponse, User } from '@/features/auth/types'
export type {
  AiSkillLibraryItem,
  ApiCaseGenerateTask,
  ApiCaseGenerateTaskRun,
  ApiCaseGenerateTaskRunImportAssertRule,
  ApiCaseGenerateTaskRunImportCase,
  ApiCaseGenerateTaskRunImportConflict,
  ApiCaseGenerateTaskRunImportExtractRule,
  ApiCaseGenerateTaskRunImportStatus,
  ApiCaseGenerateTaskRunImportedTarget,
  ApiCaseGenerateTaskRunReviewStatus,
  ApiCaseGenerateTaskRunStatus,
  ApiCaseGenerateTaskRunSnapshot,
  ApiCaseGenerateTaskSourceType,
  CreateApiCaseGenerateTaskPayload,
  CreateFunctionalCaseGenerateTaskPayload,
  CreateRequirementAnalysisTaskPayload,
  FunctionalCaseGenerateTask,
  FunctionalCaseGenerateTaskRun,
  FunctionalCaseGenerateTaskRunSnapshot,
  FunctionalCaseGenerateTaskStage,
  FunctionalCaseGenerateTaskStageStatus,
  FunctionalCaseGenerateTaskSourceType,
  ImportApiCaseGenerateTaskRunPayload,
  ImportApiCaseGenerateTaskRunResult,
  RequirementAnalysisTask,
  RequirementAnalysisTaskRun,
  RequirementAnalysisTaskRunSnapshot,
  RequirementAnalysisTaskSourceType,
  ReviewApiCaseGenerateTaskRunPayload,
  ReviewFunctionalCaseGenerateTaskRunPayload,
  ReviewFunctionalCaseGenerateTaskRunStagePayload,
  RunFunctionalCaseGenerateTaskPayload,
  RunRequirementAnalysisTaskPayload,
  UpdateApiCaseGenerateTaskPayload,
  UpdateApiCaseGenerateTaskRunResultPayload,
  UpdateFunctionalCaseGenerateTaskPayload,
  UpdateFunctionalCaseGenerateTaskRunStageOutputPayload,
  UpdateRequirementAnalysisTaskPayload,
  UploadAiSkillPayload,
} from '@/features/ai-testing/types'
export type {
  ApiAssertComparator,
  ApiAssertRule,
  ApiAssertSource,
  ApiCase,
  ApiCaseRunAssertResult,
  ApiCaseRunExtractResult,
  ApiCaseRunRequestSnapshot,
  ApiCaseRunResponseSnapshot,
  ApiCaseRunResult,
  ApiCaseRunStatus,
  ApiCollection,
  ApiCollectionImportResult,
  ApiCollectionRunItem,
  ApiCollectionRunReport,
  ApiCollectionRunSummary,
  ApiEnvironment,
  ApiEnvironmentVar,
  ApiExtractRule,
  ApiExtractRuleSource,
  CreateApiAssertRulePayload,
  CreateApiCasePayload,
  CreateApiCollectionPayload,
  CreateApiEnvironmentPayload,
  CreateApiEnvironmentVarPayload,
  CreateApiExtractRulePayload,
  RunApiCasePayload,
  RunApiCollectionPayload,
  UpdateApiAssertRulePayload,
  UpdateApiCasePayload,
  UpdateApiCollectionPayload,
  UpdateApiEnvironmentPayload,
  UpdateApiEnvironmentVarPayload,
  UpdateApiExtractRulePayload,
} from '@/features/api-automation/types'
export type {
  CreateTestReportGenerateRunPayload,
  Project,
  ProjectUpdatePayload,
  Sprint,
  SprintCreatePayload,
  SprintDailyMetricsSnapshot,
  SprintDailyMetricsTestStats,
  SprintUpdatePayload,
  TestReportGenerateRun,
  TestReportGenerateRunSnapshot,
  TestReportGenerateRunStatus,
} from '@/features/projects/types'
export type {
  Requirement,
  RequirementCreatePayload,
  RequirementDocumentType,
  RequirementUpdatePayload,
} from '@/features/requirements/types'
export type {
  CreateZentaoBindingPayload,
  CreateZentaoConnectionPayload,
  IntegrationConnectionStatus,
  LlmConnection,
  CreateLlmConnectionPayload,
  UpdateLlmConnectionPayload,
  UpdateZentaoConnectionPayload,
  ZentaoBindingTargetType,
  ZentaoBinding,
  ZentaoConnection,
  ZentaoRemoteListResponse,
  ZentaoRemoteOption,
} from '@/features/base-services/types'
export type {
  CreateFunctionTestCasePayload,
  CreateFunctionTestSuitePayload,
  FunctionTestCase,
  FunctionTestCaseImportResult,
  FunctionTestCaseZentaoImportItem,
  FunctionTestCaseZentaoImportResult,
  FunctionTestSuite,
  ImportFunctionTestCasesToZentaoPayload,
  UpdateFunctionTestCasePayload,
  UpdateFunctionTestSuitePayload,
} from '@/features/test-cases/types'
export type {
  CreateUiTestCasePayload,
  CreateUiTestSuitePayload,
  UiTestCase,
  UiScreenshotPolicy,
  UiTestCaseDebugRunPayload,
  UiTestCaseRun,
  UiTestCaseRunStepResult,
  RunUiTestSuitePayload,
  UiTestSuiteImportResult,
  UiTestSuite,
  UiTestSuiteRunItem,
  UiTestSuiteRunReport,
  UiTestSuiteRunSummary,
  UpdateUiTestCasePayload,
  UpdateUiTestSuitePayload,
} from '@/features/ui-automation/types'

export type { ApiEnvelope, ListResponse } from '@/shared/api/request'
export { ApiError, listItems, listTotal } from '@/shared/api/request'

export const api = {
  ...authApi,
  ...aiTestingApi,
  ...baseServicesApi,
  ...projectsApi,
  ...requirementsApi,
  ...apiAutomationApi,
  ...functionTestingApi,
  ...uiAutomationApi,
}
